[project]
name = "projeto-circuitos-gq1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "M10Legend2", email = "moisesflopesf@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
]

# [project.scripts]
# projeto-circuitos-gq1 = "projeto_circuitos_gq1:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
